version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    working_dir: /app/frontend 
    tty: true

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    ports:
      - "8000:8000"
    working_dir: /var/www/html/backend
    volumes:
    - ./backend:/var/www/html/backend
  db:
    container_name: db
    build:
      context: ./.docker/db
      dockerfile: Dockerfile
    ports:  
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql:cached
    environment:
      MYSQL_DATABASE: portfolio-laravel-react
      MYSQL_USER: portfolio-laravel-react
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
volumes:
  db_data:
